name: sticker_memo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  qr_code_scanner: ^1.0.1
  http: ^1.2.2
  table_calendar: ^3.0.3
  intl: any
  image_picker: ^0.8.4+11
  file_picker: ^8.0.6
  flutter_sound: ^9.2.13
  flutter_sound_platform_interface: ^9.2.15
  audioplayers: ^5.2.0
  path_provider: ^2.0.9
  permission_handler: ^10.0.0
  envied: ^0.5.4+1
  shared_preferences: ^2.0.6
  convert: ^3.0.1
  flutter_secure_storage: ^9.2.2
  video_player: ^2.2.15
  geocoding: ^2.0.5
  flutter_document_picker: ^5.0.0
  file_saver: ^0.2.14
  record: ^4.0.0
  flutter_ffmpeg: ^0.4.0
  socket_io_client: ^2.0.3+1
  flutter_local_notifications: ^17.2.2
  flutter_webrtc: ^0.11.7
  docx_to_text: ^1.0.1
  flutter_pptx: ^0.1.3
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.7
  webview_flutter_wkwebview: ^3.14.0
  flutter_inappwebview: ^6.0.0
  open_file: ^3.5.3
  multi_image_picker_view: ^1.1.0
  url_launcher: ^6.3.0
  sdp_transform: ^0.3.2
  flutter_background: ^1.3.0+1
  extended_text_field: ^15.0.0
  path: ^1.9.0
  flutter_pdf_text: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  fonts:
    - family: IBMPlexSansKR
      fonts:
        - asset: assets/fonts/IBMPlexSansKR-Light.ttf

  assets:
    - assets/images/
