name: sticker_memo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  qr_code_scanner: ^1.0.1
  http: ^1.2.2
  table_calendar: ^3.0.3
  intl: any
  image_picker: ^0.8.4+11
  file_picker: ^8.0.6
  flutter_sound: ^9.2.13
  flutter_sound_platform_interface: ^9.2.15
  audioplayers: ^5.2.0
  path_provider: ^2.0.9
  permission_handler: ^10.0.0
  envied: ^0.5.4+1
  shared_preferences: ^2.0.6
  convert: ^3.0.1
  flutter_secure_storage: ^9.2.2
  video_player: ^2.2.15
  geocoding: ^2.0.5
  flutter_document_picker: ^5.0.0
  file_saver: ^0.2.14
  record: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/
